// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGsSqyeWAg5chK4CLiSxoEktJmURHMn-s',
    appId: '1:763661840962:web:1d0629cafa8e52414bf3db',
    messagingSenderId: '763661840962',
    projectId: 'ssnhi-app',
    authDomain: 'ssnhi-app.firebaseapp.com',
    storageBucket: 'ssnhi-app.firebasestorage.app',
    measurementId: 'G-DFDQ4HR6KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzxHNWIsyv18SzMJIKsW0hcQpC6rUzDaI',
    appId: '1:763661840962:android:2f16c0202b3b261c4bf3db',
    messagingSenderId: '763661840962',
    projectId: 'ssnhi-app',
    storageBucket: 'ssnhi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9FVEyGET4iHM9aeOVnxNLveuU71FnM2M',
    appId: '1:763661840962:ios:edacac8c44b58b284bf3db',
    messagingSenderId: '763661840962',
    projectId: 'ssnhi-app',
    storageBucket: 'ssnhi-app.firebasestorage.app',
    iosBundleId: 'com.example.ssnhiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9FVEyGET4iHM9aeOVnxNLveuU71FnM2M',
    appId: '1:763661840962:ios:edacac8c44b58b284bf3db',
    messagingSenderId: '763661840962',
    projectId: 'ssnhi-app',
    storageBucket: 'ssnhi-app.firebasestorage.app',
    iosBundleId: 'com.example.ssnhiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGsSqyeWAg5chK4CLiSxoEktJmURHMn-s',
    appId: '1:763661840962:web:4510de67abee54004bf3db',
    messagingSenderId: '763661840962',
    projectId: 'ssnhi-app',
    authDomain: 'ssnhi-app.firebaseapp.com',
    storageBucket: 'ssnhi-app.firebasestorage.app',
    measurementId: 'G-1F1PK7NSLE',
  );
}
